### ISSUE TITLE
Support for combined transport types (Cycling + Ferry and Cycling + Public Transport) in TravelTime API POST request

### ISSUE THREAD

**Issue by sampeters1** [traveltime-dev/traveltime-python-sdk#85]
I'm generating isochrones via a POST request to the TravelTime API and want to set transportation to `Cycling + Ferry` and `Cycling + Public Transport`. However, it seems I can only select one from `PublicTransport`, `Driving`, `Ferry`, `Walking`, `Cycling`, or `DrivingTrain`. 

Is there no support for these combined transport types in a Python POST request?

**Comment by arnasbr** [comment]
`Cycling + Ferry` is already present under the `Ferry` transportation type, example:
```scala
    results = await sdk.time_map_geojson_async(
        coordinates=[Coordinates(lat=41.507609, lng=-0.128315)],
        departure_time=datetime.now(),
        transportation=Ferry(type="cycling+ferry"),
    )
```

Same applies to `Driving + Ferry`

Currently in the process of adding support for `Cycling + Public Transport`

**Comment by sampeters1** [comment]
Thanks for clarifying!

**Comment by sampeters1** [comment]
I'm currenlty using traveltimepy versions 3.7.0. Under which Class is `Cycling + Public Transport` present?

`Cycling(type="cycling+public_transport")` gives

`ValidationError: 1 validation error for Cycling type unexpected value; permitted: 'cycling' (type=value_error.const; given=cycling+public_transport; permitted=('cycling',))`
  
while  `PublicTransport(type="cycling+public_transport")` results in

`ValidationError: 1 validation error for PublicTransport
type unexpected value; permitted: 'public_transport', 'train', 'bus', 'coach' (type=value_error.const; given=cycling+public_transport; permitted=('public_transport', 'train', 'bus', 'coach'))`

**Comment by arnasbrad** [comment]
Sorry for the late reply.

https://github.com/traveltime-dev/traveltime-python-sdk/blob/master/traveltimepy/dto/transportation.py

You are getting this error, because `cycling+public_transport` is not implemented under the `PublicTransport` class.

`cycling+public_transport` has it's own separate class (see the picture):

![image](https://github.com/traveltime-dev/traveltime-python-sdk/assets/45391480/558e3524-7383-4ae4-be58-37cbd10e32c8)

to use it, instead of `PublicTransport(type="cycling+public_transport")`, you would simply do `CyclingPublicTransport()`. Let me know if you have any more questions!

**Comment by arnasbr** [comment]
Sorry for the late reply.

https://github.com/traveltime-dev/traveltime-python-sdk/blob/master/traveltimepy/dto/transportation.py

You are getting this error, because `cycling+public_transport` is not implemented under the `PublicTransport` class.

`cycling+public_transport` has it's own separate class (see the picture):

![image](https://github.com/traveltime-dev/traveltime-python-sdk/assets/45391480/558e3524-7383-4ae4-be58-37cbd10e32c8)

to use it, instead of `PublicTransport(type="cycling+public_transport")`, you would simply do `CyclingPublicTransport()`. Let me know if you have any more questions!
